name: Code Checks

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_checks:
        strategy:
            matrix:
                actions:
                    -
                        name: Tests
                        run: vendor/bin/phpunit
                php-versions: ['7.4', '8.0']

        runs-on: ubuntu-latest
        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
